services:

  # Movies API
  movies-api:
    image: doconnor/movies-api:1.0
    container_name: movies-api
    ports:
      - '9000:9000'
    environment:
      MONGODB_URI: mongodb://admin:password@mongo:27017/movies
      REDIS_URI: redis://redis
      ENABLE_WRITING_HANDLERS: 'false'
    depends_on:
      - mongo
      - redis
    networks:
      - backend

  # MongoDB
  mongo:
    image: mongo:8.0-rc
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"  # MongoDB port
    networks:
      - backend

  # Mongo Express
  mongo-express:
    image: mongo-express:1.0-20-alpine3.19
    container_name: mongo-express
    ports:
      - "8081:8081"  # Mongo Express port
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo
    networks:
      - backend

  # Redis
  redis:
    image: redis:alpine
    container_name: redis
    networks: 
      - backend

networks:
  backend:
    driver: bridge  

volumes:
  mongo_data: