services:

  api:
    image: doconnor/movies-api:1.0
    container_name: movies-api
    ports:
      - '9000:9000'

  # Movies API
  movies-api:
    image: doconnor/movies-api:1.0
    ports:
      - "5000:5000"  # Movies API port
    environment:
      MONGODB_URI: "mongodb://mongo:27017"
      REDIS_URI: "redis://redis:6379"
      ENABLE_WRITING_HANDLERS: "false"
    depends_on:
      - mongo
      - redis

  # MongoDB
  mongo:
    image: mongo:8.0-rc
    environment:
      MONGO_INITDB_ROOT_USERNAME: "admin"
      MONGO_INITDB_ROOT_PASSWORD: "password"
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"  # MongoDB port

  # Redis
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"  # Redis port